const fs = require('fs');

const richExplanations = {
    "derivada_cadena": "<b>Tipo:</b> Regla de Derivación<br><br><b>¿Por qué es correcto?</b> La regla de la cadena nos dice que derivemos de afuera hacia adentro: derivas la función exterior y la multiplicas por la derivada de lo de adentro.<br><br><b>Errores comunes:</b> Es incorrecto derivar ambas funciones por separado y multiplicarlas, siempre debes evaluar la derivada exterior usando la función interior original.",
    "derivada_potencia": "<b>Tipo:</b> Fórmula Directa<br><br><b>¿Por qué es correcto?</b> Para derivar una potencia, bajas el exponente multiplicando al frente y le restas 1 al exponente original.<br><br><b>Errores comunes:</b> No sumes 1 al exponente (eso se hace en las integrales), y recuerda siempre restar 1.",
    "integral_fracciones_parciales": "<b>Tipo:</b> Reordenamiento Algebraico (Previo a integrar)<br><br><b>¿Por qué es correcto?</b> Cuando tienes factores multiplicándose en el denominador, no hay fórmula directa. Debes separar la fracción en sumas de fracciones más sencillas usando constantes A y B.<br><br><b>Errores comunes:</b> Tratar de integrar el denominador directamente con logaritmo; primero debes separar las fracciones.",
    "integral_partes": "<b>Tipo:</b> Método de Integración<br><br><b>¿Por qué es correcto?</b> Se usa cuando hay multiplicación de funciones sin relación de derivada. Recuerda la mnemotecnia: \"Un Día Vi Una Vaca Menos Vestida De Uniforme\".<br><br><b>Errores comunes:</b> Integrar ambas funciones por separado y multiplicarlas es un error matemático muy grave.",
    "integral_completar_diferencial": "<b>Tipo:</b> Identificación de Patrones<br><br><b>¿Por qué es correcto?</b> Tomas la parte más compleja como 'u', la derivas para obtener 'du' y si sobra una constante, la pasas dividiendo (balanceo) para que la ecuación no se altere.<br><br><b>Errores comunes:</b> Si intentas sustituir directamente sin calcular 'du', te faltará el balanceo de la constante de integración.",
    "integral_sustitucion_general": "<b>Tipo:</b> Método de Sustitución (Cambio de variable)<br><br><b>¿Por qué es correcto?</b> Si ves una función anidada y su derivada multiplicándola afuera, puedes sustituir todo eso por 'u' y 'du' para transformarla en una integral básica.<br><br><b>Errores comunes:</b> Confundirlo con integración por partes. Aquí sí hay relación de derivada entre las partes de la función.",
    "integral_potencia": "<b>Tipo:</b> Fórmula Directa<br><br><b>¿Por qué es correcto?</b> Es la operación inversa a la derivada: le sumas 1 al exponente, y el resultado lo pones dividiendo abajo.<br><br><b>Errores comunes:</b> Restar 1 al exponente (eso es derivar), o intentar usar esta regla cuando el exponente es -1 (eso da un logaritmo).",
    "identidad_pitagorica": "<b>Tipo:</b> Identidad Trigonométrica (Sustitución equivalente)<br><br><b>¿Por qué es correcto?</b> Esta no es una fórmula para \"resolver\", sino una equivalencia basada en el Teorema de Pitágoras. Te sirve para reescribir la ecuación y hacerla más fácil.<br><br><b>Errores comunes:</b> Creer que seno más coseno es 1, ¡tienen que estar al cuadrado!",
    "propiedades_logaritmicas_producto": "<b>Tipo:</b> Propiedad Algebraica (Reescritura)<br><br><b>¿Por qué es correcto?</b> Los logaritmos transforman multiplicaciones internas en sumas externas, y divisiones en restas. Es una regla para desarmar ecuaciones.<br><br><b>Errores comunes:</b> Pensar que ln(a + b) es igual a ln(a) + ln(b). ¡La suma interna NO se puede separar!",
    "propiedades_logaritmicas_potencia": "<b>Tipo:</b> Propiedad Algebraica (Reescritura)<br><br><b>¿Por qué es correcto?</b> El exponente dentro de un logaritmo \"se cae\" hacia el frente y pasa a multiplicar a todo el logaritmo. Ayuda a eliminar exponentes molestos.<br><br><b>Errores comunes:</b> Confundir el exponente del argumento interno con elevar todo el logaritmo al cuadrado: ln(a^2) no es lo mismo que (ln(a))^2.",
    "ley_exponentes": "<b>Tipo:</b> Ley de los Exponentes (Aritmética básica)<br><br><b>¿Por qué es correcto?</b> Si multiplicas bases iguales, sus exponentes se suman. Si elevas una potencia a otra potencia, se multiplican.<br><br><b>Errores comunes:</b> Multiplicar los exponentes cuando se están sumando las bases, o sumarlos cuando es potencia de potencia.",
    "binomio_conjugado": "<b>Tipo:</b> Producto Notable (Expansión rápida)<br><br><b>¿Por qué es correcto?</b> Al multiplicar una suma por su respectiva resta (conjugados), los términos del medio se cancelan, dejando solo el cuadrado del primero menos el cuadrado del segundo.<br><br><b>Errores comunes:</b> Creer que es igual a (a-b)^2, el cual generaría un trinomio.",
    "binomio_cubo": "<b>Tipo:</b> Producto Notable (Expansión rápida)<br><br><b>¿Por qué es correcto?</b> Sigue la regla fija: el cubo del primero, triple del cuadrado del primero por el segundo, triple del primero por el cuadrado del segundo, y el cubo del segundo.<br><br><b>Errores comunes:</b> Pensar que (a+b)^3 es simplemente a^3 + b^3. Te estás comiendo los términos del medio.",
    "suma_diferencia_cubos": "<b>Tipo:</b> Factorización (Reordenamiento algebraico)<br><br><b>¿Por qué es correcto?</b> Extraes las raíces cúbicas y las multiplicas por un trinomio parecido al cuadrado perfecto, pero con el signo de en medio cambiado y sin el 2.<br><br><b>Errores comunes:</b> Confundirlo con el binomio al cubo (a-b)^3.",
    "binomio_cuadrado": "<b>Tipo:</b> Producto Notable (Expansión rápida)<br><br><b>¿Por qué es correcto?</b> Al desarrollar (a+b)(a+b), obtienes: el primero al cuadrado, más el doble del primero por el segundo, más el segundo al cuadrado.<br><br><b>Errores comunes:</b> Escribir que (a+b)^2 = a^2 + b^2 (Error de novato muy común, falta el 2ab del medio).",
    "diferencia_cuadrados": "<b>Tipo:</b> Factorización (Reordenamiento algebraico)<br><br><b>¿Por qué es correcto?</b> Si tienes dos cuadrados que se están restando, es el proceso inverso al binomio conjugado: abres dos paréntesis, en uno sumas sus raíces y en el otro las restas.<br><br><b>Errores comunes:</b> Intentar factorizar una SUMA de cuadrados (a^2 + b^2); eso no se puede factorizar en los números reales.",
    "trinomio_cuadrado_perfecto": "<b>Tipo:</b> Factorización (Reordenamiento algebraico)<br><br><b>¿Por qué es correcto?</b> Si el primer y tercer término tienen raíz cuadrada exacta y el del medio es el doble de multiplicar esas raíces, lo factorizas comprimiéndolo en un Binomio al Cuadrado.<br><br><b>Errores comunes:</b> Factorizarlo como si fuera una diferencia de cuadrados o no verificar que el término del medio sea exactamente el doble.",
    "division_polinomios": "<b>Tipo:</b> Reordenamiento Algebraico (División larga)<br><br><b>¿Por qué es correcto?</b> Funciona exactamente igual que en primaria: el resultado total es el cociente obtenido más lo que sobró (residuo) dividido entre el divisor original.<br><br><b>Errores comunes:</b> Restar el numerador y denominador directamente, o cancelar términos que se están sumando."
};

let content = fs.readFileSync('js/app.js', 'utf-8');

for (const [id, richText] of Object.entries(richExplanations)) {
    const idRegex = new RegExp("id:\\s*'" + id + "'[\\s\\S]*?explanation:\\s*'(.*?)'");
    content = content.replace(idRegex, (match, oldExplanation) => {
        return match.replace("explanation: '" + oldExplanation + "'", "explanation: `" + richText + "`");
    });
}

fs.writeFileSync('js/app.js', content, 'utf-8');
console.log('Explicaciones enriquecidas añadidas correctamente.');
